# Generated by Django 5.2 on 2025-05-04 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='image',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='file_path',
            field=models.FileField(max_length=255, upload_to='songs/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='video_url',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='video/'),
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatrooms_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatrooms_user2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chatrooms',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('srcfile', models.FileField(blank=True, max_length=255, null=True, upload_to='chatfiles/')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('song', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.song')),
                ('chatroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.chatroom')),
            ],
            options={
                'db_table': 'chatmessages',
            },
        ),
        migrations.CreateModel(
            name='AlbumFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.album')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'album_favorites',
                'unique_together': {('user', 'album')},
            },
        ),
        migrations.CreateModel(
            name='PlaylistFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.playlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'playlist_favorites',
                'unique_together': {('user', 'playlist')},
            },
        ),
    ]
