# Generated by Django 5.2 on 2025-04-21 01:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='created_by_id',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='albumsong',
            old_name='album_id',
            new_name='album',
        ),
        migrations.RenameField(
            model_name='albumsong',
            old_name='song_id',
            new_name='song',
        ),
        migrations.RenameField(
            model_name='download',
            old_name='song_id',
            new_name='song',
        ),
        migrations.RenameField(
            model_name='download',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='song_id',
            new_name='song',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='follower',
            old_name='artist_id',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='follower',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='receiver_id',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sender_id',
            new_name='sender',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='artist_id',
            new_name='artist',
        ),
        migrations.AlterUniqueTogether(
            name='albumsong',
            unique_together={('album', 'song')},
        ),
        migrations.AlterUniqueTogether(
            name='download',
            unique_together={('user', 'song')},
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'song')},
        ),
        migrations.AlterUniqueTogether(
            name='follower',
            unique_together={('user', 'artist')},
        ),
    ]
